[project]
name = "archilog"
version = "0.2"
description = "A simple project for educational purpose."
readme = "README.md"
dependencies = [
    "click>=8.1.7",
    "flask>=3.1.0",
    "flask-httpauth>=4.8.0",
    "flask-wtf>=1.2.2",
    "httpauth>=0.4.1",
    "sqlalchemy>=2.0.40",
]
requires-python = ">=3.10"


[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"


[project.scripts]
archilog = "archilog.views.cli:cli"
